### ISSUE TITLE
[Feature Request] Add Multi-Libraries support

### ISSUE THREAD

**Issue by lucashsantosb** [Kesomannen/gale#121]
I have multiple SSDs and is pretty annoying needing to select only one Steam Library for my games...

**Comment by Kesomannen** [comment]
How do you intend for this to work? The steam library option is only a "default" for Gale to find your game installation, since you can override it per game. If you could specify multiple libraries, I'm guessing you'd have to pick it for each game in a drop down anyway, which doesn't seem like a big step up from overriding the path.

**Comment by Kesomannen** [comment]
I think the current solution covers the problem well enough, so I'll close this
