### ISSUE TITLE
[Feature Request] Better Modpack Support

### ISSUE THREAD

**Issue by PenguCCN** [Kesomannen/gale#124]
I run a decently sized modpack and r2modman leaves a LOT to be desired.

Since they haven't implemented this I hope you could!

Would it be possible to compare manifests between releases and update accordingly? Here's an example:

**0.5.2

- Removed MetalRecharging

0.5.1

- Added MetalRecharging**

Since MetalRecharging was present in the prior release but not current, it should be removed. This allows modpack creators to better maintain mod compatibility and give every user the same experience without running into mod incompatibility issues that are simply caused by leftover mods meant to be removed.

A lot of people simply recommend deleting the mod profile and redownloading, however I feel as if that's a band-aid solution and could be handled better.

Obviously it should ignore any mods that aren't included in the manifest before, so user added mods should remain. 

Also updating the modpack should also update all included dependencies to the versions mentioned in the manifest as well.

**Comment by Kesomannen** [comment]
I've also thought about this, but I think a better solution is to have a new type of profile that is centered around a single modpack. This profile would be unchangeable, except for updating the modpack itself, which would sync the profile's mods to exactly the pack's dependencies. 

We don't want this behavior in normal profiles, since then QoL/"additive" modpacks would be really annoying to work with.
