### ISSUE TITLE
[Suggestion] Add page tab numbers / One long list

### ISSUE THREAD

**Issue by SeymourSchlong** [Kesomannen/gale#16]
![image](https://github.com/Kesomannen/gale/assets/36908123/271dde80-c01a-451b-acaa-f03705fb4b5b)

It's hard to understand the following:
- How many mods I have installed
- How many mods are listed per page
- How many pages of mods there are to flip through
- How to go to any given page (cannot go from page 1 to 4 directly)

If possible, maybe it could be added that the installed mod list has no pages?
In addition, possibly add the page numbers like traditional websites have (as well as maybe a text input for going to a specific page)
![image](https://github.com/Kesomannen/gale/assets/36908123/fec447f7-8dfc-47b6-97b4-68c43eb2b1c6)

**Comment by Kesomannen** [comment]
I'm actually testing having an infinite scroll instead of pages right now, not sure which I like more. I think I'll include it in the next update, get some feedback, and go from there. Of course it could be a toggle in the settings, but that comes with extra complexity and maintenance.

If I were to go back to pages, I'll definitely make it more similar to r2modman/TMM.

I also made a little mod counter for the profiles
![bild](https://github.com/Kesomannen/gale/assets/113015915/bf409e38-3dab-404a-9575-cb5bafb87465)

**Comment by SeymourSchlong** [comment]
wonderful! thank you for your hard work ♥
