### ISSUE TITLE
Add an option to not use a mod cache

### ISSUE THREAD

**Issue by JarheadHME** [Kesomannen/gale#170]
I had issues with r2mm at some point that seemed to be solved by disabling the use of a mod cache, and my internet speed is good enough that I really don't care about the extra time to manually redownload the files any time I'm getting new ones, nor the disk space they take up.

**Comment by Kesomannen** [comment]
Are you getting any issues with Gale?

**Comment by JarheadHME** [comment]
No, it's partially also personal preference, I feel a little better knowing that the files are freshly downloaded, and would appreciate an option :)

**Comment by Kesomannen** [comment]
Well, Gale's cache is more "involved" and it would require quite a few changes to add that option. The cache also actually saves space by linking files to instead of copying them to each profile, meaning each mod is only stored on your disk once in the cache. Disabling it would basically only be detrimental. So I don't think a feature like that is worth implementing for the small amount of people that would use it.
