### ISSUE TITLE
Kitchen Sink of Issues and Suggestions :)

### ISSUE THREAD

**Issue by Test-Account666** [Kesomannen/gale#2]
Hello!

You mod manager feels really good and I'd like to see it grow.

I do have some issues/suggestions for you though ^^

Issues:
- XDG error:
  `Failed to execute 'open_config_file' - Failed to open config file /home/entity303/.local/share/com.kesomannen.gale/lethal-company/profiles/Default/BepInEx/config/BepInEx.cfg: Launcher "xdg-open" "/home/entity303/.local/share/com.kesomannen.gale/lethal-company/profiles/Default/BepInEx/config/BepInEx.cfg" failed with ExitStatus(unix_wait_status(1024)).`
  
  Not sure if this issue is on my end or if it has something to do with gale though.

- Gale always throws a fit when something unexpected happens
  Examples:
  - If the default value in a config is higher than the allowed value (Not per se a problem, but maybe just ignore this?)
  - Unexpected directories inside the `com.kesomannen.gale` directory (Talking to you `localstorage` directory)

Suggestions:
- Add support for importing profiles in file format
- When importing a profile, allow the user to choose between options, if something unexpected happens (Like not being able to find a mod). Options could be "Ignore", "Cancel", "Delete"
- Allow us to import profiles under different names
- Allow us to overwrite (Or how TS calls it "Update") a profile
- Add an option to either deactivate the "Home Page" button or move it. This is just a personal issue, but I keep clicking on it, expecting my mod list
- Make the context menu follow the dark theme (The menu that allows you to reload and stuff)
- Make popups like the "Delete profile" popup also follow the dark theme (Or just do an internal popup instead)
- Instead of wasting most of the screen space with nothing, show the `Details` section underneath the short description when browsing mods (See image for further context)
- Add ability to also disable mods

![waste](https://github.com/Kesomannen/gale/assets/36412486/d97ef75b-f269-4b75-a801-67e7802955a4)

It could look like this:
![example](https://github.com/Kesomannen/gale/assets/36412486/6a4bb810-17cf-4b20-b092-400305fc8b5b)

**Comment by Kesomannen** [comment]
Thanks for the suggestions! The first issue is probably on your end or on the rust crate's end (https://crates.io/crates/open). The other two I have fixed and trying to fix some other config parsing issues. For the suggestions:
1. Planned and pretty quick to add.
2. Not too sure about this one, I would have to make some bigger code changes and doesnt feel like it happens that often?
3. Yeah should definitely add this
4. Same for this
5. I also thought about this, maybe I'll move it to the bottom. I was close to removing it, but I couldnt figure out how to redirect to the mod list automatically (since it isn't at the index route) (I'm a bit new to web development).
6. The right-click menu is from the webview itself, so I dont think I can control that. Will look into it though
7. Maybe I'll change this to a dialog inside of the app. I thought a native dialog was fitting because it's a pretty consequential action. Also was just easier to implement xD
8. I do agree on this, but sounds a bit too complicated for now. It has to do a fetch request to get the README, which could look a bit odd if you're switching between mods (having a spinner appear and disappear over and over). Also it's a bit tough on the implementation side, and I have to account for when the description is too long or the window too small. Maybe some more experienced web dev could pull it off, but I'm probably leaving it like it is for now.
9. This is also planned, I just have to look into how exactly r2modman/thunderstore do it.

**Comment by TheBlackEntity** [comment]
> 2. Not too sure about this one, I would have to make some bigger code changes and doesnt feel like it happens that often?
Yeah... It usually doesn't occur.

> 5. I also thought about this, maybe I'll move it to the bottom. I was close to removing it, but I couldnt figure out how to redirect to the mod list automatically (since it isn't at the index route) (I'm a bit new to web development).
I think moving it to the bottom would be nice.

Maybe also switch the position of the "Browse mods" and "Manage profile" button?
I think that would be more intuitive.
Could just be my muscle memory speaking though...

> 6. The right-click menu is from the webview itself, so I dont think I can control that. Will look into it though
You should at least be able to block it and make your own.
Not sure how much work that is though...

> 7. Maybe I'll change this to a dialog inside of the app. I thought a native dialog was fitting because it's a pretty consequential action. Also was just easier to implement xD
I personally hate native dialogs, since they never seem to act as they should xd

But I understand that you chose the easier route xD

> 8. I do agree on this, but sounds a bit too complicated for now. [...] Maybe some more experienced web dev could pull it off, but I'm probably leaving it like it is for now.
Well, I hope you can implement this at some point :)

> 9. This is also planned, I just have to look into how exactly r2modman/thunderstore do it.
Pretty sure they just rename the dll file to `<modname>.dll.old` and call it a day 🤔

**Comment by TheBlackEntity** [comment]
Oh... There's one more bug I'd like to mention.

For some reason I can *always* resize the application.

Even when maximized.

This sometimes leads to me accidentally resizing the window instead of moving it to my other monitor

**Comment by TheBlackEntity** [comment]
Two new suggestions:

- Don't show deprecated mods by default (Or make it toggleable)
- Negative filters. E.g. categories that I'd like to exclude from my search

**Comment by TheBlackEntity** [comment]
Another one:
- List mods to update before you actually update them

That would ensure that the user doesn't accidentally update mods

**Comment by TheBlackEntity** [comment]
A new issue discovered:
- Some config entries are not shown in the config editor

When editing some configs, I noticed that some of them are too short.

Well, turns out Gale hides some entries for some reason

**Comment by TheBlackEntity** [comment]
Hope you're not overwhelmed 😅 

`Failed to execute 'query_mods_in_profile' - Package with id c59bda38-e6de-4483-87b7-ecc34b490760 not found.`

**Comment by TheBlackEntity** [comment]
Suggestions Time! :)

- Allow uninstalling of dependencies without uninstalling dependents

This is crucial, if you have a mod targeting another as dependency, but you want to use a fork of said dependency

**Comment by Kesomannen** [comment]
> For some reason I can always resize the application.

Doesn't for me on Windows, so probably something your desktop environment 🤷 

> Don't show deprecated mods by default (Or make it toggleable)

It is already toggleable in the `Filters` dropdown. I do plan to improve on the filtering later, will probably make something similar to how they do it on thunderstore.io

> Some config entries are not shown in the config editor

Not sure why this would be happening, could you share more more details?

> Failed to execute 'query_mods_in_profile' - Package with id c59bda38-e6de-4483-87b7-ecc34b490760 not found.
> If that happens, I can no longer see any mods in my profile

This is due to going to the profile page while mods are still being fetched. I've thought about some fixes, but havent got to actually implementing any yet.

> Allow uninstalling of dependencies without uninstalling dependents

This is already done for 0.3.0

**Comment by Kesomannen** [comment]
I think everything here is actually implemented by now lol
