### ISSUE TITLE
Switching games improvement

### ISSUE THREAD

**Issue by Smxrez** [Kesomannen/gale#23]
If you favorite a game and click on the change game button it drops down a list like the profile swaping feature
in order to access the entire library of games like it is currently you could double click or press the expand menu button. (would look like the new profile button for profiles) 
![image](https://github.com/Kesomannen/gale/assets/119914646/59704a11-8a35-4555-83d2-ef3859026b83)
![image](https://github.com/Kesomannen/gale/assets/119914646/9fc5638d-f0de-4023-b90f-3d794bd2538a)

**Comment by Kesomannen** [comment]
Maybe, but I feel like that people are not changing games that often to merit a separate display. The current solution is also the same amount of clicks with just a different kind of modal. Actually fewer clicks if you want to select a non-favorite game.

I don't think double click would be that intuitive, especially since it's not used anywhere else in the app. Most people would probably miss it and just use the dropdown.
