### ISSUE TITLE
Upgrading from 0.40 results in a loop reinstalling the same version

### ISSUE THREAD

**Issue by NeatWolf** [Kesomannen/gale#8]
![image](https://github.com/Kesomannen/gale/assets/6001560/3052cb55-e554-453d-ab0f-f40c50603b81)

Hi - for some obscure reason after pressing [Yes] in this dialogue, it seems to have opened a prompt, started an installation, and, well, opened v0.40 again (and showing the very same dialogue again - Pressing [Yes] just closes it and relaunches it, with no new "setup" being launched).

Not a huge issue as I can just install it manually, but - that's definitely not the intended behaviour ^^

After manually downloading Gale Setup v0.4.1, this puzzling screenshot:
![image](https://github.com/Kesomannen/gale/assets/6001560/5709de49-c8a8-4e76-aba5-09f34a09a0e7)
Seems to suggest v0.4.1 was already installed? 

After choosing New/Reinstall, it managed to actually install v0.4.1 (!)

**Comment by Kesomannen** [comment]
Yeah, Tauris auto updater seems really buggy. Will 100% look into and fix

**Comment by Kesomannen** [comment]
Ok, if you install with the .msi instead of the .exe it should work. I'll update the install instructions in the README too

**Comment by NeatWolf** [comment]
Apologies for coming up with these silly issues - I'm just trying to put myself in the shoes of an average user - this one was a bit confusing :P 

Thanks for addressing this! This is already almost functional - the UX is already way smoother than the alternatives!

(Is there any chance to also have a portable Win64 version among the releases? Just a zipped folder ready to use)

**Comment by Kesomannen** [comment]
No it's completely understandable, I was also really confused by this. Tauri should definitely add a disclaimer to the docs the auto updater doesn't work with NSIS (the .exe installer). Or maybe it's just a bug with their system, idk.

Also, later I will make my own update flow instead of Tauri's built in popup thingy, as it's not very user friendly at all.

> (Is there any chance to also have a portable Win64 version among the releases? Just a zipped folder ready to use)

Probably not, sadly. Tauri does produce a standalone executable when you build, but it requires you have some extra dependencies to run. The app also still stores all the mods and cache in your appdata. I could possibly make it store those directly with the .exe, but then they wouldn't retain between updates (at least not without a lot of manual file moving). On top of that, auto updates wouldn't work and I would need to figure out how to get the Tauri github action to output the standalone .exe.

All in all I don't think it's worth the hassle, as most people are fine or might even prefer a proper installation.

**Comment by VL4DST3R** [comment]
> I could possibly make it store those directly with the .exe
+1 for this! I would really like to have gale more self-contained so we can transfer it and its configs between devices more easily.
Being able to store the mod files on different drives would be very nice but can't really be done currently as the config points to a single data folder.
